name: laplace_pg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pytorch=1.13.1
  - pytorch-lightning=1.8.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - polars=0.15.14
  - numpy=1.24.1
  - pandas=1.5.3
  - scikit-learn=1.2.0
  - jupyterlab=3.5.3
  - matplotlib=3.6.3
  - notebook=6.5.2
  - plotly=5.13.0
  - fire=0.4.0
  - tqdm=4.64.1
  - ipywidgets=7.6.5
  - tensorboard=2.11.2
  - pip:
    - laplace-torch
